name: Build and Publish Docker Image to DockerHub

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Laravel image Build
        run: |
          docker build -t "${{ secrets.DOCKERHUB_USERNAME }}/docker-image" .
      - name: Laravel image Push
        run: |
          docker push "${{ secrets.DOCKERHUB_USERNAME }}/docker-image"